---

- name: Ensure dependencies are installed
  ansible.builtin.dnf:
    name: "{{ veracrypt_fedora_dependencies }}"
    state: present

- name: Copy Veracrypt public key to managed node
  ansible.builtin.copy:
    src: VeraCrypt_PGP_public_key.asc
    dest: /tmp/VeraCrypt_PGP_public_key.asc
    mode: "0644"

- name: Install Veracrypt public key
  ansible.builtin.rpm_key:
    key: /tmp/VeraCrypt_PGP_public_key.asc
    state: present

- name: Build Veracrypt download URL
  ansible.builtin.set_fact:
    veracrypt_package_url: >-
      {{ [
        veracrypt_base_download_url,
        'veracrypt/VeraCrypt/releases/download',
        'VeraCrypt_' ~ veracrypt_version,
        'veracrypt-console-' ~ veracrypt_version ~
        '-Fedora-' ~ ansible_distribution_major_version ~ '-x86_64.rpm'
      ] | map('trim', '/') | join('/') }}

- name: Display built Veracrypt download URL
  ansible.builtin.debug:
    var: veracrypt_package_url

- name: Build Veracrypt package path
  ansible.builtin.set_fact:
    veracrypt_package_dst: >-
      {{ [ 
        '/tmp',
        'veracrypt-console-' ~ veracrypt_version ~
        '-Fedora-' ~ ansible_distribution_major_version ~ '-x86_64.rpm'
      ] | path_join }}

- name: Display built Veracrypt package path
  ansible.builtin.debug:
    var: veracrypt_package_dst

- name: Download VeraCrypt package
  ansible.builtin.get_url:
    url: "{{ veracrypt_package_url }}"
    dest: "{{ veracrypt_package_dst }}"

- name: Install veracrypt package
  ansible.builtin.dnf:
    name: "{{ veracrypt_package_dst }}"
    state: present
