---
- name: Verify
  hosts: molecule
  gather_facts: true

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Fail if veracrypt-console is not installed
      ansible.builtin.fail:
        msg: "veracrypt-console package is not installed"
      when: "'veracrypt-console' not in ansible_facts.packages"

    - name: Include Debian verify file
      ansible.builtin.include_tasks: tasks/verify-debian.yml
      when:
        - ansible_facts.distribution == 'Debian'

    - name: Include Fedora verify file
      ansible.builtin.include_tasks: tasks/verify-fedora.yml
      when:
        - ansible_facts.distribution == 'Fedora'
