---
- name: Verify
  hosts: molecule
  gather_facts: true

  tasks:
    - name: Include Debian verify file
      ansible.builtin.include_tasks: tasks/verify-debian.yml
      when:
        - ansible_facts.distribution == 'Debian'

    - name: Include Fedora verify file
      ansible.builtin.include_tasks: tasks/verify-fedora.yml
      when:
        - ansible_facts.distribution == 'Fedora'
